---
name: KeepInventory
api: 4.0.0
author: NhanAZ
version: 0.0.1
main: NhanAZ\KeepInventory\Main
website: https://github.com/NhanAZ
src-namespace-prefix: NhanAZ\KeepInventory
description: Keep items in the player's inventory after they die
...
