---
name: KeepInv
api: 4.0.0
author: NhanAZ
version: 1.0.0
main: NhanAZ\KeepInv\Main
website: https://github.com/NhanAZ
src-namespace-prefix: NhanAZ\KeepInv
description: Keep items in the player's inventory after they die
...
