---
# KeepInventory
#
# Value: true or false
# Default value: true (Recomend using)
#
# Value description:
# KeepInventory: true (Items in the player's inventory will be kept after the they die)
# KeepInventory: false (Items in the player's inventory will be lost after the they die)
KeepInventory: true

# MessageAfterDeath
#
# Value: true or false
# Default value: false (Recomend using)
#
# Value description:
# MessageAfterDeath: true (A message telling the player that their items are kept after they die)
# MessageAfterDeath: false (There is no notification to the player that their items are kept after they die)
MessageAfterDeath: false


# MessageToPlayerAfterDeath
#
# Value: "MessageToPlayerAfterDeath (String)"
# Default value: §aItems in your inventory have been kept
#
# Value description: Notifications sent to players after they die
MessageToPlayerAfterDeath: "§aItems in your inventory have been kept"

# Message types
#
# Value: message, popup, tip, title, subtitle, actionbarmessage
# Default value: message (Recomend using)
#
# Value description:
# MessageType: message (Sends a direct chat message to a player)
# MessageType: title (Send a title text to the user's screen)
# MessageType: popup (Sends a popup message to the player)
# MessageType: tip (Sends a tip message to the player)
# MessageType: actionbarmessage (Send a small text to the user's screen.)
MessageType: message

# Notices
#
# Value: true or false
# Default value: true (Recomend using)
#
# Value description:
# Notices: true (Notifications related to this plugin will be displayed on the console)
# Notices: false (Notifications related to this plugin will not be displayed on the console)
Notices: true
...
